default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%='postgres'%>
  password: <%='123'%>
  host: <%='localhost'%>
  port: 5433

development:
  <<: *default
  database: music_dating_app_development

test:
  <<: *default
  database: music_dating_app_test

production:
  <<: *default
  database: music_dating_app_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>